### PR TITLE
Scrappily updated for Blender 2.8

### PR DESCRIPTION
**Pull request by darloth**
There is an annotation warning and it's not the cleanest update, I'm sure others can and probably should do better - but it loads the model and puts the texture on the model.

### CODE REVIEW

**Comment by Anarchid** [comment]
The total whitespace change makes it impossible to see what exactly you changed though. 

Is that necessary in new Blender? If no, would be cleaner to reformat to whatever indents the original uses.

**Comment by darloth** [comment]
That annoyed me too, I couldn't initially figure out what it was.  Thanks for pointing out it was whitespace - I think it's because Blender's editor just has an opinion by default as to what the whitespace should be.

**Comment by sanguinariojoe** [comment]
Hey!

Fortunately the diff can be correctly visualized with [Meld](https://meldmerge.org/).

The main problem I see to this PR is the lack of backward compatibility. Let's see if I can achieve something that is working fine in 2.80 and 2.7x.

Thanks!

**Comment by sanguinariojoe** [comment]
Tested on Blender 2.79b and 2.80

**Comment by ashdnazg** [comment]
in the future when there's lots of shitespace just add ?w=1 in the end of the diff URL like so:

https://github.com/sanguinariojoe/blender_s3o_import/pull/1/files?w=1

**Pull request merged**
